theme: jekyll-theme-cayman # do not change this line

title: "BizLens: Startup Success Evaluator."
description: "Shirina Daniel"
image: "https://raw.githubusercontent.com/shirinadan/ai4all-of.github.io/main/ChatGPT%20Image%20Aug%2015%2C%202025%2C%2012_06_38%20AM.png"
