theme: jekyll-theme-cayman # do not change this line

title: "BizLens: Startup Success Evaluator"
description: Shirina Daniel
description: An AI-powered tool to predict startup success.
image: "https://github.com/shirinadan/ai4all-of.github.io/blob/main/ChatGPT%20Image%20Aug%2015%2C%202025%2C%2012_06_38%20AM.png"
