theme: jekyll-theme-cayman # do not change this line

description: Shirina Daniel
title: "BizLens: Startup Success Evaluator"
description: "An AI-powered tool to predict startup success."
image: "/logo.png"
